
services:
  api-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cpp-api-server
    ports:
      - "8080:8080"
    environment:
      - ENV=production
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a reverse proxy with nginx
  nginx:
    image: nginx:alpine
    container_name: cpp-api-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api-server
    restart: unless-stopped